services:
  frontend-service:
    build: ./frontend
    image: frontend
    command: npm run dev
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules        # preserve node_modules in container
  backend-service:
    build: ./backend
    image: backend
    command: nodemon ./backend/index.js 3000
    container_name: backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules        # preserve node_modules in container

  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./backend/models/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: docker
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://docker:1234@mongo:27017/
      ME_CONFIG_BASICAUTH: false
