pipeline{
    agent {
            docker {
            filename 'Dockerfile.dev'
            // label 'react-app-test'
            dir 'jenkins-reactjs-app'
        }
    }
    
    stages{
        stage("Testings"){
            steps{
                 echo "========Testing========"
                 sh 'docker run  react-app-test npm run test'
            }
        }
    }
}

