pipeline{
    agent {
            dockerfile {
            filename 'Dockerfile.dev'
            // label 'react-app-test'
            dir 'jenkins-reactjs-app'
        }
    }
    
    stages{
        stage("Testings"){
            steps{
                 echo "========Testing========"
                //  sh 'docker run  react-app-test npm run test'
                sh 'pwd'
                dir("/var/jenkins_home/workspace/react-app/jenkins-reactjs-app/"){

                
                    sh 'node -v'
                    sh 'npm -v'
                    sh 'ls -l'
                    sh 'npm install'
                    sh 'npm run test '
                    sh 'ls -l'
                }
            }
        }
    }
}

