pipeline{
    agent any
    
    stages{
        stage("Docker Build"){
            steps{
                echo "========BUILDING========"
                sh 'docker build -t react-app-test:latest -f Dockerfile.dev .'
            }
      
        }

        stage("Testings"){
            steps{
                 echo "========Testing========"
                 sh 'docker run  react-app-test npm run test'
            }
        }
    }
}