services:
  jenkins:
    build: .
    container_name: jenkins_docker
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_net
    ports:
      - 8080:8080
      - 50000:50000

volumes:
  jenkins_home:

networks:
  jenkins_net: